export const householdAdmins = [
  {
    id: "HA-001",
    householdName: "The Patterson Family",
    adminEmail: "m.patterson@email.com",
    plan: "PRO",
    deviceCount: 3,
    createdDate: "2025-08-14",
    status: "Active",
  },
  {
    id: "HA-002",
    householdName: "Greenfield Residence",
    adminEmail: "s.greenfield@email.com",
    plan: "PRO",
    deviceCount: 2,
    createdDate: "2025-09-02",
    status: "Active",
  },
  {
    id: "HA-003",
    householdName: "The Morales Household",
    adminEmail: "l.morales@email.com",
    plan: "FREE",
    deviceCount: 1,
    createdDate: "2025-10-21",
    status: "Active",
  },
  {
    id: "HA-004",
    householdName: "Chen Family Home",
    adminEmail: "d.chen@email.com",
    plan: "PRO",
    deviceCount: 4,
    createdDate: "2025-07-03",
    status: "Active",
  },
  {
    id: "HA-005",
    householdName: "The O'Brien Estate",
    adminEmail: "k.obrien@email.com",
    plan: "FREE",
    deviceCount: 1,
    createdDate: "2025-11-15",
    status: "Suspended",
  },
  {
    id: "HA-006",
    householdName: "Williams Care Home",
    adminEmail: "j.williams@email.com",
    plan: "PRO",
    deviceCount: 5,
    createdDate: "2025-06-28",
    status: "Active",
  },
  {
    id: "HA-007",
    householdName: "The Nakamura Residence",
    adminEmail: "a.nakamura@email.com",
    plan: "PRO",
    deviceCount: 2,
    createdDate: "2025-12-01",
    status: "Active",
  },
  {
    id: "HA-008",
    householdName: "Rivera Household",
    adminEmail: "c.rivera@email.com",
    plan: "FREE",
    deviceCount: 1,
    createdDate: "2026-01-10",
    status: "Active",
  },
];

export const subscriptions = [
  {
    id: "SUB-001",
    household: "The Patterson Family",
    plan: "PRO",
    status: "Active",
    deviceLimit: 5,
    renewalDate: "2026-08-14",
    paymentStatus: "Paid",
  },
  {
    id: "SUB-002",
    household: "Greenfield Residence",
    plan: "PRO",
    status: "Active",
    deviceLimit: 5,
    renewalDate: "2026-09-02",
    paymentStatus: "Paid",
  },
  {
    id: "SUB-003",
    household: "The Morales Household",
    plan: "FREE",
    status: "Active",
    deviceLimit: 1,
    renewalDate: "—",
    paymentStatus: "—",
  },
  {
    id: "SUB-004",
    household: "Chen Family Home",
    plan: "PRO",
    status: "Active",
    deviceLimit: 5,
    renewalDate: "2026-07-03",
    paymentStatus: "Paid",
  },
  {
    id: "SUB-005",
    household: "The O'Brien Estate",
    plan: "FREE",
    status: "Suspended",
    deviceLimit: 1,
    renewalDate: "—",
    paymentStatus: "—",
  },
  {
    id: "SUB-006",
    household: "Williams Care Home",
    plan: "PRO",
    status: "Active",
    deviceLimit: 10,
    renewalDate: "2026-06-28",
    paymentStatus: "Paid",
  },
  {
    id: "SUB-007",
    household: "The Nakamura Residence",
    plan: "PRO",
    status: "Active",
    deviceLimit: 5,
    renewalDate: "2026-12-01",
    paymentStatus: "Overdue",
  },
  {
    id: "SUB-008",
    household: "Rivera Household",
    plan: "FREE",
    status: "Active",
    deviceLimit: 1,
    renewalDate: "—",
    paymentStatus: "—",
  },
];

export const devices = [
  {
    id: "DEV-4A82F1",
    household: "The Patterson Family",
    location: "Living Room",
    status: "Online",
    registeredDate: "2025-08-15",
    lastActive: "2026-02-22T09:14:00",
  },
  {
    id: "DEV-4A82F2",
    household: "The Patterson Family",
    location: "Master Bedroom",
    status: "Online",
    registeredDate: "2025-08-15",
    lastActive: "2026-02-22T09:12:00",
  },
  {
    id: "DEV-4A82F3",
    household: "The Patterson Family",
    location: "Hallway",
    status: "Offline",
    registeredDate: "2025-09-01",
    lastActive: "2026-02-20T18:30:00",
  },
  {
    id: "DEV-7B93D1",
    household: "Greenfield Residence",
    location: "Kitchen",
    status: "Online",
    registeredDate: "2025-09-03",
    lastActive: "2026-02-22T09:10:00",
  },
  {
    id: "DEV-7B93D2",
    household: "Greenfield Residence",
    location: "Bedroom",
    status: "Online",
    registeredDate: "2025-09-03",
    lastActive: "2026-02-22T09:08:00",
  },
  {
    id: "DEV-3C12A1",
    household: "The Morales Household",
    location: "Living Room",
    status: "Online",
    registeredDate: "2025-10-22",
    lastActive: "2026-02-22T08:55:00",
  },
  {
    id: "DEV-9D45E1",
    household: "Chen Family Home",
    location: "Living Room",
    status: "Online",
    registeredDate: "2025-07-04",
    lastActive: "2026-02-22T09:05:00",
  },
  {
    id: "DEV-9D45E2",
    household: "Chen Family Home",
    location: "Den",
    status: "Online",
    registeredDate: "2025-07-04",
    lastActive: "2026-02-22T08:50:00",
  },
  {
    id: "DEV-9D45E3",
    household: "Chen Family Home",
    location: "Bedroom 1",
    status: "Offline",
    registeredDate: "2025-08-10",
    lastActive: "2026-02-19T22:15:00",
  },
  {
    id: "DEV-9D45E4",
    household: "Chen Family Home",
    location: "Bedroom 2",
    status: "Online",
    registeredDate: "2025-08-10",
    lastActive: "2026-02-22T09:00:00",
  },
  {
    id: "DEV-5F78B1",
    household: "The O'Brien Estate",
    location: "Living Room",
    status: "Offline",
    registeredDate: "2025-11-16",
    lastActive: "2026-01-28T14:00:00",
  },
  {
    id: "DEV-6G21C1",
    household: "Williams Care Home",
    location: "Room A",
    status: "Online",
    registeredDate: "2025-06-29",
    lastActive: "2026-02-22T09:13:00",
  },
  {
    id: "DEV-6G21C2",
    household: "Williams Care Home",
    location: "Room B",
    status: "Online",
    registeredDate: "2025-06-29",
    lastActive: "2026-02-22T09:11:00",
  },
  {
    id: "DEV-6G21C3",
    household: "Williams Care Home",
    location: "Common Area",
    status: "Online",
    registeredDate: "2025-07-15",
    lastActive: "2026-02-22T09:09:00",
  },
  {
    id: "DEV-6G21C4",
    household: "Williams Care Home",
    location: "Corridor",
    status: "Online",
    registeredDate: "2025-07-15",
    lastActive: "2026-02-22T09:07:00",
  },
  {
    id: "DEV-6G21C5",
    household: "Williams Care Home",
    location: "Room C",
    status: "Offline",
    registeredDate: "2025-08-20",
    lastActive: "2026-02-21T23:45:00",
  },
  {
    id: "DEV-8H34D1",
    household: "The Nakamura Residence",
    location: "Living Room",
    status: "Online",
    registeredDate: "2025-12-02",
    lastActive: "2026-02-22T09:06:00",
  },
  {
    id: "DEV-8H34D2",
    household: "The Nakamura Residence",
    location: "Bedroom",
    status: "Online",
    registeredDate: "2025-12-02",
    lastActive: "2026-02-22T09:04:00",
  },
  {
    id: "DEV-2J56F1",
    household: "Rivera Household",
    location: "Living Room",
    status: "Online",
    registeredDate: "2026-01-11",
    lastActive: "2026-02-22T08:58:00",
  },
];

export const fallAlerts = [
  {
    id: "FA-001",
    timestamp: "2026-02-22T08:42:00",
    deviceId: "DEV-4A82F1",
    householdName: "The Patterson Family",
    residentName: "Margaret Patterson",
    confidence: 94,
    status: "NEW",
  },
  {
    id: "FA-002",
    timestamp: "2026-02-22T07:18:00",
    deviceId: "DEV-6G21C3",
    householdName: "Williams Care Home",
    residentName: "Robert Williams",
    confidence: 88,
    status: "ACKNOWLEDGED",
  },
  {
    id: "FA-003",
    timestamp: "2026-02-22T03:55:00",
    deviceId: "DEV-9D45E1",
    householdName: "Chen Family Home",
    residentName: "Mei-Ling Chen",
    confidence: 97,
    status: "RESOLVED",
  },
  {
    id: "FA-004",
    timestamp: "2026-02-21T22:30:00",
    deviceId: "DEV-7B93D1",
    householdName: "Greenfield Residence",
    residentName: "Harold Greenfield",
    confidence: 91,
    status: "RESOLVED",
  },
  {
    id: "FA-005",
    timestamp: "2026-02-21T19:12:00",
    deviceId: "DEV-6G21C1",
    householdName: "Williams Care Home",
    residentName: "Dorothy Evans",
    confidence: 85,
    status: "RESOLVED",
  },
  {
    id: "FA-006",
    timestamp: "2026-02-21T14:45:00",
    deviceId: "DEV-8H34D1",
    householdName: "The Nakamura Residence",
    residentName: "Kenji Nakamura",
    confidence: 92,
    status: "RESOLVED",
  },
  {
    id: "FA-007",
    timestamp: "2026-02-21T11:08:00",
    deviceId: "DEV-3C12A1",
    householdName: "The Morales Household",
    residentName: "Elena Morales",
    confidence: 79,
    status: "RESOLVED",
  },
  {
    id: "FA-008",
    timestamp: "2026-02-22T09:01:00",
    deviceId: "DEV-6G21C4",
    householdName: "Williams Care Home",
    residentName: "Frank Turner",
    confidence: 96,
    status: "NEW",
  },
];

export const systemHealth = [
  { service: "API Gateway", status: "Operational" },
  { service: "PostgreSQL Database", status: "Operational" },
  { service: "Upload Service", status: "Operational" },
  { service: "Fall Detection Service", status: "Operational" },
];
